services: 

  nexus_redis: 
    image: redis:alpine
    container_name: nexus_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nexus_net


volumes: 
  redis_data:

networks: 
  nexus_net:
    driver: bridge